apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
  labels:
    app: filebeat
data:
  filebeat.yml: |-
    setup.template.enabled: true
    setup.template.settings:
      index.number_of_shards: 10
    filebeat.config:
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          host: ${NODE_NAME}
          hints.enabled: true
          labels.dedot: true
          #hints.default_config:
          #  type: container
          #  paths:
              #- /var/log/containers/nginx-ingress-controller*.log
          #    - /var/log/containers/*.log
          templates:
            - condition:
                equals:
                  kubernetes.namespace: "kube-system"
              config:
               - type: container
                  paths:
                    - /var/log/containers/*.log
            - condition:
               equals:
                  kubernetes.namespace: "default"
              config:
                - type: container
                  paths:
                    - /var/log/containers/*.log
    processors:
      - add_cloud_metadata:
      - add_host_metadata:
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"
      - drop_event.when:
            or:
            - equals:
                kubernetes.namespace: "kube-system"
            - equals:
                kubernetes.namespace: "default"
    output.logstash:
      hosts: ["${LOGSTASH_HOST}:${LOGSTASH_PORT}"]
      ssl.certificate_authorities: ["${SSL_CRT}"]
      ssl.certificate: "${SSL_CRT}"
      ssl.key: "${SSL_KEY}"
    logging.level: info
    logging.to_files: false
    logging.files:
      path: /var/log/filebeat
      name: filebeat
      keepfiles: 7
      permissions: 0644