apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    app: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.15.0
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:
        - name: LOGSTASH_HOST
          value: "kibana.amanu.xyz"
        - name: LOGSTASH_PORT
          value: "5044"
        - name: SSL_CRT
          value: "/etc/ssl/certs/elk-ssl.crt"
        - name: SSL_KEY
          value: "/etc/ssl/cert/elk-ssl.key"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 128Mi
            cpu: 60m
          requests:
            cpu: 50m
            memory: 75Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: cert
          mountPath: /etc/ssl/certs/elk-ssl.crt
          subPath: elk-ssl.crt
        - name: key
          mountPath: /etc/ssl/cert/elk-ssl.key
          subPath: elk-ssl.key
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: filebeat-config
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
      - name: data
        hostPath:
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate
      - name: cert
        configMap:
          name: elk-ssl-crt
      - name: key
        configMap:
          name: elk-ssl-key
      nodeSelector:
        kubernetes.io/os: linux